
services:
  fastapi-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - ./symbiont/tmp:/tmp
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    command: "uvicorn symbiont.main:app --host 0.0.0.0 --port 8000 --reload"
    profiles: ["dev"]

  fastapi-prod:
    build:
      context: .
      target: production
    ports:
      - "80:8080"
    env_file:
      - .env.production
    command: "uvicorn symbiont.main:app --host 0.0.0.0 --port 8080"
    profiles: ["production"]
