version: "3.8"

services:
  fastapi-app:
    build: .
    volumes:
      - .:/app
      - ./symbiont/tmp:/tmp
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: "uvicorn symbiont.src.main:app --host 0.0.0.0 --port 8000"
