name: Build and Push to Staging Artifact Registry

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:

  push:
    branches: ["dev"]

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  PROJECT_ID: symbiont-backend
  REGION: us-central1
  REPOSITORY: staging-registry
  IMAGE: fastapi-staging

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - id: "auth"
        name: 'Authenticate to Google Cloud'
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.ARTIFACT_REGISTRY_KEY }}"
          token_format: 'access_token'
      
      - name: Build image
        run: docker build . --target production --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest

      - uses: 'docker/login-action@v1'
        name: 'Docker login'
        with:
          registry: '${{ env.REGION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      
      - name: Push image
        run: docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE --all-tags
        
